-- Snowflake user creation
-- Step 1: Use an admin role
USE ROLE ACCOUNTADMIN;

-- Step 2: Create the `transform` role and assign it to ACCOUNTADMIN
CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Step 3: Create a default warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;


DROP USER IF EXISTS dbt_test_user;

-- Step 4: Create the `dbt_test_user` user and assign to the transform role
CREATE OR REPLACE USER dbt_test_user
  PASSWORD='sourabh1251'
  LOGIN_NAME='dbt-test-user'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE=TRANSFORM
  --DEFAULT_NAMESPACE='MEDICAL.DEV'
  COMMENT='dbt_test_user user used for data transformation';
ALTER USER dbt_test_user SET TYPE = LEGACY_SERVICE;
GRANT ROLE TRANSFORM TO USER dbt_test_user;

-- Step 5: Create a database and schema for the MEDICAL project
CREATE DATABASE IF NOT EXISTS MEDICAL;
CREATE SCHEMA IF NOT EXISTS MEDICAL.DEV;
CREATE SCHEMA IF NOT EXISTS MEDICAL.PROD;
CREATE SCHEMA IF NOT EXISTS MEDICAL.TEST;
CREATE SCHEMA IF NOT EXISTS MEDICAL.RAW;

-- Step 6: Grant permissions to the `transform` role
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE MEDICAL TO ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE MEDICAL TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE MEDICAL TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA MEDICAL.DEV TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA MEDICAL.DEV TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA MEDICAL.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA MEDICAL.RAW TO ROLE TRANSFORM;
