USE ROLE ACCOUNTADMIN;

-- ==========================================
-- 1. BASE INFRASTRUCTURE (DB & SCHEMAS)
-- ==========================================
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS MEDICAL;
CREATE SCHEMA IF NOT EXISTS MEDICAL.DEV;
CREATE SCHEMA IF NOT EXISTS MEDICAL.PROD;
CREATE SCHEMA IF NOT EXISTS MEDICAL.TEST;
CREATE SCHEMA IF NOT EXISTS MEDICAL.RAW;
CREATE SCHEMA IF NOT EXISTS MEDICAL.AUDIT;

-- ==========================================
-- 2. DBT TRANSFORMATION (Role & User)
-- ==========================================
CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

DROP USER IF EXISTS dbt_test_user;
CREATE USER dbt_test_user
    PASSWORD='TempPassword123!'
    LOGIN_NAME='dbt-test-user'
    MUST_CHANGE_PASSWORD=FALSE
    DEFAULT_WAREHOUSE='COMPUTE_WH'
    DEFAULT_ROLE=TRANSFORM
    COMMENT='User used for dbt data transformation'
    TYPE=LEGACY_SERVICE;

-- Assign public key (Replace string with actual key)
ALTER USER dbt_test_user SET RSA_PUBLIC_KEY = 'putyourpublichere_withouttheBEGINandENDPUBLICKEY_and_inoneline';

GRANT ROLE TRANSFORM TO USER dbt_test_user;

-- Grants for TRANSFORM role
GRANT OPERATE, USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT USAGE ON DATABASE MEDICAL TO ROLE TRANSFORM;

GRANT ALL ON ALL SCHEMAS IN DATABASE MEDICAL TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE MEDICAL TO ROLE TRANSFORM;

GRANT ALL ON ALL TABLES IN SCHEMA MEDICAL.DEV TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA MEDICAL.DEV TO ROLE TRANSFORM;

GRANT ALL ON ALL TABLES IN SCHEMA MEDICAL.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA MEDICAL.RAW TO ROLE TRANSFORM;

GRANT INSERT ON TABLE MEDICAL.AUDIT.DEPLOYMENT_HISTORY_DBT_MODEL TO ROLE TRANSFORM;
GRANT INSERT ON TABLE MEDICAL.AUDIT.DEPLOYMENT_HISTORY_GITHUB_ACTION TO ROLE TRANSFORM;

-- ==========================================
-- 3. CI/CD WORKLOADS (Role & User)
-- ==========================================
CREATE ROLE IF NOT EXISTS CICD_ROLE
    COMMENT = 'CICD project: Warehouse for CICD workloads';

CREATE USER IF NOT EXISTS CICD_USER
    DEFAULT_ROLE = CICD_ROLE
    DEFAULT_WAREHOUSE = COMPUTE_WH
    MUST_CHANGE_PASSWORD = FALSE;

-- Assign public key (Replace string with actual key)
ALTER USER CICD_USER SET RSA_PUBLIC_KEY = 'putyourpublichere_withouttheBEGINandENDPUBLICKEY_and_inoneline';

GRANT ROLE CICD_ROLE TO USER CICD_USER;

-- Grants for CICD_ROLE
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE CICD_ROLE;
GRANT USAGE ON DATABASE MEDICAL TO ROLE CICD_ROLE;
GRANT USAGE ON SCHEMA MEDICAL.AUDIT TO ROLE CICD_ROLE;
GRANT CREATE SCHEMA ON DATABASE MEDICAL TO ROLE CICD_ROLE;

-- Future Grants for CICD_ROLE
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE MEDICAL TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE MEDICAL TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE MEDICAL TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN DATABASE MEDICAL TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN DATABASE MEDICAL TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN DATABASE MEDICAL TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STREAMS IN DATABASE MEDICAL TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TASKS IN DATABASE MEDICAL TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE PIPES IN DATABASE MEDICAL TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN DATABASE MEDICAL TO ROLE CICD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS IN DATABASE MEDICAL TO ROLE CICD_ROLE;

-- Specific Schema Table Grants for CICD_ROLE
GRANT ALL ON ALL SCHEMAS IN DATABASE MEDICAL TO ROLE CICD_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA MEDICAL.DEV TO ROLE CICD_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA MEDICAL.DEV TO ROLE CICD_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA MEDICAL.RAW TO ROLE CICD_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA MEDICAL.RAW TO ROLE CICD_ROLE;

-- Object Specific Grants for CICD_ROLE
GRANT CREATE ALERT ON ALL SCHEMAS IN DATABASE MEDICAL TO ROLE CICD_ROLE;
GRANT CREATE STREAMLIT ON ALL SCHEMAS IN DATABASE MEDICAL TO ROLE CICD_ROLE;
GRANT INSERT, SELECT ON TABLE MEDICAL.AUDIT.DEPLOYMENT_HISTORY_GITHUB_ACTION TO ROLE CICD_ROLE;

-- ==========================================
-- 4. TERRAFORM PROVISIONING (Role & User)
-- ==========================================
CREATE ROLE IF NOT EXISTS TERRAFORM_ROLE;

CREATE USER IF NOT EXISTS TERRAFORM_USER
    PASSWORD = 'StrongPassword'
    DEFAULT_ROLE = TERRAFORM_ROLE
    DEFAULT_WAREHOUSE = COMPUTE_WH
    MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE TERRAFORM_ROLE TO USER TERRAFORM_USER;

-- Grants for TERRAFORM_ROLE
GRANT CREATE DATABASE ON ACCOUNT TO ROLE TERRAFORM_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE TERRAFORM_ROLE;
GRANT CREATE ROLE ON ACCOUNT TO ROLE TERRAFORM_ROLE;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE TERRAFORM_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TERRAFORM_ROLE;