-- Snowflake user creation
-- Step 1: Use an admin role
USE ROLE ACCOUNTADMIN;

-- Step 2: Create the `transform` role and assign it to ACCOUNTADMIN
CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Step 3: Create a default warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;


DROP USER IF EXISTS dbt_test_user;

-- Step 4: Create the `dbt_test_user` user and assign to the transform role
CREATE OR REPLACE USER dbt_test_user
  PASSWORD='TempPassword123!'
  LOGIN_NAME='dbt-test-user'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE=TRANSFORM
  --DEFAULT_NAMESPACE='MEDICAL.DEV'
  COMMENT='dbt_test_user user used for data transformation';

ALTER USER dbt_test_user SET TYPE = LEGACY_SERVICE;
GRANT ROLE TRANSFORM TO USER dbt_test_user;

-- Step 5: Create a database and schema for the MEDICAL project
CREATE DATABASE IF NOT EXISTS MEDICAL;
CREATE SCHEMA IF NOT EXISTS MEDICAL.DEV;
CREATE SCHEMA IF NOT EXISTS MEDICAL.PROD;
CREATE SCHEMA IF NOT EXISTS MEDICAL.TEST;
CREATE SCHEMA IF NOT EXISTS MEDICAL.RAW;

-- Step 6: Grant permissions to the `transform` role
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE MEDICAL TO ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE MEDICAL TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE MEDICAL TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA MEDICAL.DEV TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA MEDICAL.DEV TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA MEDICAL.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA MEDICAL.RAW TO ROLE TRANSFORM;




-- 1. Grant usage on the database and schema
GRANT USAGE ON DATABASE MEDICAL TO ROLE TRANSFORM;
GRANT USAGE ON SCHEMA MEDICAL.AUDIT TO ROLE TRANSFORM;

-- 2. Grant permission to insert data into the specific table
GRANT INSERT ON TABLE MEDICAL.AUDIT.DEPLOYMENT_HISTORY_DBT_MODEL TO ROLE TRANSFORM;

-- 2. Grant permission to insert data into the specific table
GRANT INSERT ON TABLE MEDICAL.AUDIT.DEPLOYMENT_HISTORY_GITHUB_ACTION TO ROLE TRANSFORM;



CREATE OR REPLACE ROLE TERRAFORM_ROLE;
GRANT ROLE TERRAFORM_ROLE TO USER TERRAFORM_USER;

CREATE OR REPLACE USER TERRAFORM_USER
PASSWORD = 'StrongPassword'
DEFAULT_ROLE = TERRAFORM_ROLE
DEFAULT_WAREHOUSE = COMPUTE_WH
MUST_CHANGE_PASSWORD = FALSE;


GRANT CREATE DATABASE ON ACCOUNT TO ROLE TERRAFORM_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE TERRAFORM_ROLE;
GRANT CREATE ROLE ON ACCOUNT TO ROLE TERRAFORM_ROLE;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE TERRAFORM_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TERRAFORM_ROLE;



GRANT ROLE TERRAFORM_ROLE TO USER TERRAFORM_USER;
ALTER USER TERRAFORM_USER SET DEFAULT_ROLE = TERRAFORM_ROLE;