name: dbt prod CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
  SNOWFLAKE_SCHEMA: prod
  SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dbt_project

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install dbt-core dbt-snowflake sqlfluff sqlfluff-templater-dbt

      - name: Install dbt dependencies
        run: dbt deps

      - name: Validate dbt connection
        run: dbt debug --profiles-dir . --target prod

      - name: Parse dbt project
        run: dbt parse --target prod

      - name: Run lint check
        run: sqlfluff lint models --dialect snowflake
        env:
          DBT_TARGET: prod

      - name: Run dbt build
        run: dbt build --target prod
