name: dbt incremental daily load

on:
  workflow_dispatch:
  schedule:
    # This runs at 02:00 UTC every day.
    - cron: '0 2 * * *'

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
  
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_DBT_USER }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_DBT_ROLE }}
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_DBT_PRIVATE_KEY_PASSPHRASE }}
  SNOWFLAKE_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_DBT_PRIVATE_KEY_RAW }}

jobs:
  dbt_daily_run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dbt_project

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install dbt-core dbt-snowflake sqlfluff sqlfluff-templater-dbt

      - name: Install dbt dependencies
        run: dbt deps

      - name: Run daily incremental load and snapshot
        run: dbt build --select dim_patients fact_visits --target prod
        
      - name: Setup Snowflake CLI
        if: always()
        uses: snowflakedb/snowflake-cli-action@v2

      - name: Log GitHub Action Orchestration
        if: always()
        env:
          # Snowflake CLI expects these specific environment variables for zero-config authentication
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_CICD_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_CICD_ROLE }}
          SNOWFLAKE_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_CICD_PRIVATE_KEY_RAW }}
          PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_CICD_PRIVATE_KEY_PASSPHRASE }}
          SNOWFLAKE_AUTHENTICATOR: SNOWFLAKE_JWT
        run: |
          snow sql -x -q "INSERT INTO MEDICAL.AUDIT.DEPLOYMENT_HISTORY_GITHUB_ACTION (GH_RUN_ID, BRANCH_NAME, WORKFLOW_NAME, COMMIT_SHA, DEPLOYMENT_STATUS, TRIGGERED_BY, TRIGGER_EVENT) VALUES ('${{ github.run_id }}', '${{ github.ref_name }}', '${{ github.workflow }}', '${{ github.sha }}', '${{ job.status }}', '${{ github.actor }}', 'DAILY_INCREMENTAL_LOAD');"

      - name: Send Email Notification on Success
        if: success() 
        uses: dawidd6/action-send-mail@v3
        with:
          # Required connection details
          server_address: smtp.gmail.com 
          server_port: 465 
          secure: true
          
          # Credentials from GitHub Secrets
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          
          # Email Metadata
          subject: "✅ dbt Deployment SUCCESS: ${{ github.event.inputs.target }}"
          to: sourabh9557151166@gmail.com # Comma-separated list for multiple recipients
          from: GitHub Actions Pipeline
          
          # The Email Body
          body: |
            The dbt deployment workflow has completed SUCCESSFULLY.
            
            Environment: ${{ github.event.inputs.target }}
            Triggered by: ${{ github.actor }}
            Branch: ${{ github.ref_name }}
            
            Click here to view the execution logs:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}          
