name: dbt incremental daily load

on:
  workflow_dispatch:
  schedule:
    # This runs at 02:00 UTC every day.
    - cron: '0 2 * * *'

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
  SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

jobs:
  dbt_daily_run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dbt_project

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install dbt-core dbt-snowflake sqlfluff sqlfluff-templater-dbt

      - name: Install dbt dependencies
        run: dbt deps

      - name: Run daily incremental load and snapshot
        run: dbt build --select dim_patients fact_visits --target prod
        
      - name: Setup Snowflake CLI
        if: always()
        uses: snowflakedb/snowflake-cli-action@v2

      - name: Log GitHub Action Orchestration
        if: always()
        run: |
          snow sql -x -q "INSERT INTO MEDICAL.AUDIT.DEPLOYMENT_HISTORY_GITHUB_ACTION (GH_RUN_ID, BRANCH_NAME, WORKFLOW_NAME, COMMIT_SHA, DEPLOYMENT_STATUS, TRIGGERED_BY, TRIGGER_EVENT) VALUES ('${{ github.run_id }}', '${{ github.ref_name }}', '${{ github.workflow }}', '${{ github.sha }}', '${{ job.status }}', '${{ github.actor }}', 'DAILY_INCREMENTAL_LOAD');"
