name: FULL DEPLOY prod/dev env

# This workflow is triggered manually from the GitHub Actions tab
on:
  workflow_dispatch:
    inputs:
      target:
        description: "Select dbt environment."
        type: choice
        required: true
        options:
          - dev
          - prod

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
  SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

jobs:
  full-deploy-snowflake:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dbt_project

    env:
      DBT_TARGET: ${{ github.event.inputs.target }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install dbt-core dbt-snowflake sqlfluff sqlfluff-templater-dbt

      - name: Install dbt dependencies
        run: dbt deps

      - name: Validate dbt connection
        run: dbt debug --profiles-dir . --target $DBT_TARGET

      - name: Parse dbt project
        run: dbt parse --target $DBT_TARGET

      - name: Run lint check
        run: sqlfluff lint models --dialect snowflake
        env:
          DBT_TARGET: $DBT_TARGET

      - name: Run dbt build
        run: dbt build --target $DBT_TARGET


