name: FULL DEPLOY prod/dev env

# This workflow is triggered manually from the GitHub Actions tab
on:
  workflow_dispatch:
    inputs:
      target:
        description: "Select dbt environment."
        type: choice
        required: true
        options:
          - dev
          - prod

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
  SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

jobs:
  full-deploy-snowflake:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dbt_project

    env:
      DBT_TARGET: ${{ github.event.inputs.target }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install dbt-core dbt-snowflake sqlfluff sqlfluff-templater-dbt

      - name: Install dbt dependencies
        run: dbt deps

      - name: Validate dbt connection
        run: dbt debug --profiles-dir . --target $DBT_TARGET

      - name: Parse dbt project
        run: dbt parse --target $DBT_TARGET

      - name: Run lint check
        run: sqlfluff lint models --dialect snowflake
        env:
          DBT_TARGET: $DBT_TARGET

      - name: Run dbt build
        env:
          # TWEAK 1: Pass the GitHub Run ID to dbt so the macro can use it as a Foreign Key
          DBT_ENV_GH_RUN_ID: ${{ github.run_id }}
        run: dbt build --target $DBT_TARGET

      - name: Upload dbt state artifact
        uses: actions/upload-artifact@v4
        if: success() # Only save the state if the build didn't fail
        with:
          # Make the artifact name dynamic so dev doesn't overwrite prod
          name: ${{ github.event.inputs.target }}-dbt-state 
          path: ./dbt_project/target/manifest.json

      - name: Setup Snowflake CLI
        if: always()
        uses: snowflakedb/snowflake-cli-action@v2

      - name: Log GitHub Action Orchestration
        if: always()
        run: |
          snow sql -q "INSERT INTO MEDICAL.AUDIT.DEPLOYMENT_HISTORY_GITHUB_ACTION (GH_RUN_ID, BRANCH_NAME, WORKFLOW_NAME, COMMIT_SHA, DEPLOYMENT_STATUS, TRIGGERED_BY, TRIGGER_EVENT) VALUES ('${{ github.run_id }}', '${{ github.ref_name }}', '${{ github.workflow }}', '${{ github.sha }}', '${{ job.status }}', '${{ github.actor }}', '${{ github.event_name }}');"


